name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - master-noro
    tags:
      - v*
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set IMAGE_NAME_LOWER
        run: echo "IMAGE_NAME_LOWER=${IMAGE_NAME,,}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME_LOWER }}:latest -t ${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }} -f ./docker/Dockerfile .
          docker push ${{ env.IMAGE_NAME_LOWER }}:latest
          docker push ${{ env.IMAGE_NAME_LOWER }}:${{ github.sha }}

      - name: Inspect image
        run: docker inspect ${{ env.IMAGE_NAME_LOWER }}:latest
